apiVersion: v1
data:
  GH_STATE: c3VjY2Vzcw==
kind: Secret
metadata:
  creationTimestamp: 2018-06-14T19:54:37Z
  labels:
    build: 01cfzxc2bvqys48v6aj5bm79vy
    component: job
    expires: "1531598077667"
    heritage: brigade
    jobname: notify-success
  name: notify-success-01cfzxc2bvqys48v6aj5bm79vy
  namespace: default
type: brigade.sh/job
